#!/bin/bash


while /usr/bin/true
do
  date=`/bin/date +%s`
  taken=`(time -p curl --silent -o /dev/null  --max-time 15 http://icons.ljtoys.org.uk/mi/foo) 2>&1`
  retval=$?
  if [ "$retval" == "0" ]; then
    real=`echo $taken | grep 'real' | cut -d ' ' -f2`
    line="${date}\t$real"
  else
    line="${date}\tFAIL"
  fi
  echo -e "$line"
  sleep 20
done

